import LandingPage from "@/components/home/views/template/LandingPage";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Luiggy | Frontend Side",
    description: "Generated by Luiggy",
};

export default function Home() {
    return <LandingPage appName="Frontend Side" />;
}
