import PollRenderer from "@/components/polls/views/template/PollRenderer";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Luiggy | Frontend Side",
    description: "Generated by Luiggy",
};

export default function Home() {
    return <PollRenderer name="Online Polls" />;
}
