version: '3.9'

services:

  db:
    image: postgres
    restart: always
    container_name: poll_db_container
    environment:
      POSTGRES_DB: polldb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data: